# Projet Fil Rouge
### Nom, Prénom, Année

## Data Cleaning

In [1]:
import pandas as pd
# On importe pandas pour lire, nettoyer et analyser les données.

df = pd.read_excel(
    "../data/raw/naissances.xlsx",
    sheet_name=1,
    skiprows=5,
    header=[0, 1]
)
# On lit le fichier Excel naissances.xlsx.
# sheet_name=1 signifie qu’on lit la deuxième feuille du fichier.
# skiprows=5 permet d’ignorer les lignes de titre/description.
# header=[0, 1] indique que les noms de colonnes sont sur deux lignes.

new_columns = []
# On crée une liste vide pour stocker les nouveaux noms de colonnes.

for col in df.columns:
    # On parcourt chaque colonne du tableau.

    niveau_1 = str(col[0]).strip()
    # On récupère le premier niveau du nom de colonne, par exemple l’année 2012.

    niveau_2 = str(col[1]).strip()
    # On récupère le deuxième niveau, par exemple naissances totales.

    if "Unnamed" in niveau_1 and "Unnamed" in niveau_2:
        new_columns.append("a_supprimer")
        # Si les deux niveaux sont vides/inutiles, on marque la colonne à supprimer.

    elif "Unnamed" in niveau_1:
        new_columns.append(niveau_2)
        # Si le premier niveau est vide, on garde seulement le deuxième niveau.

    elif "Unnamed" in niveau_2:
        new_columns.append(niveau_1)
        # Si le deuxième niveau est vide, on garde seulement le premier niveau.

    else:
        new_columns.append(f"{niveau_1}_{niveau_2}")
        # Sinon, on combine les deux niveaux : année + type d’indicateur.

df.columns = new_columns
# On remplace les anciens noms de colonnes par les nouveaux noms propres.

df = df.drop(columns=["a_supprimer"], errors="ignore")
# On supprime les colonnes inutiles repérées plus haut.

df.columns = (
    df.columns
    .str.replace(" ", "_")
    .str.replace("'", "_")
    .str.lower()
)
# On nettoie les noms : espaces remplacés par _, apostrophes remplacées, tout en minuscules.

df.head()
# On affiche les 5 premières lignes pour vérifier le résultat.

,zone_géographique,2012_naissances_totales,2012_naissances_vivantes,2013_naissances_totales,2013_naissances_vivantes,2014_naissances_totales,2014_naissances_vivantes,2015_naissances_totales,2015_naissances_vivantes,2016_naissances_totales,...,2019_naissances_totales,2019_naissances_vivantes,2020_naissances_totales,2020_naissances_vivantes,2021_naissances_totales,2021_naissances_vivantes,2022_naissances_totales,2022_naissances_vivantes,2023_naissances_totales,2023_naissances_vivantes
0,Auvergne - Rhône-Alpes,97162.0,96344.0,95854.0,95073.0,96683.0,95926.0,94586.0,93854.0,92364.0,...,89174.0,88514.0,86542.0,85873.0,87069.0,86382.0,84877.0,84219.0,78411.0,77821.0
1,Bourgogne - Franche-Comté,31467.0,31181.0,30706.0,30459.0,30447.0,30199.0,29532.0,29295.0,28553.0,...,26304.0,26086.0,25836.0,25632.0,25558.0,25314.0,24979.0,24758.0,23348.0,23160.0
2,Bretagne,36740.0,36457.0,35861.0,35559.0,35251.0,34971.0,33712.0,33445.0,32990.0,...,31518.0,31276.0,31238.0,30991.0,32088.0,31826.0,31261.0,30991.0,29113.0,28861.0
3,Centre - Val de Loire,30217.0,29917.0,29419.0,29167.0,29225.0,28984.0,27955.0,27705.0,27478.0,...,26055.0,25823.0,25506.0,25284.0,25582.0,25382.0,25375.0,25175.0,23129.0,22906.0
4,Corse,2995.0,2960.0,2920.0,2887.0,3022.0,2981.0,2873.0,2842.0,2922.0,...,2875.0,2848.0,2682.0,2662.0,2743.0,2722.0,2744.0,2720.0,2513.0,2487.0

In [2]:
#Ensuite ajoute ces cellules de contrôle :

In [3]:
df.shape
# Affiche le nombre de lignes et de colonnes.

(119, 25)

In [4]:
df.info()
# Affiche les types des colonnes et les valeurs non manquantes.

<class 'pandas.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   zone_géographique         118 non-null    str
 1   2012_naissances_totales   117 non-null    float64
 2   2012_naissances_vivantes  117 non-null    float64
 3   2013_naissances_totales   117 non-null    float64
 4   2013_naissances_vivantes  117 non-null    float64
 5   2014_naissances_totales   117 non-null    float64
 6   2014_naissances_vivantes  117 non-null    float64
 7   2015_naissances_totales   117 non-null    float64
 8   2015_naissances_vivantes  117 non-null    float64
 9   2016_naissances_totales   117 non-null    float64
 10  2016_naissances_vivantes  117 non-null    float64
 11  2017_naissances_totales   117 non-null    object
 12  2017_naissances_vivantes  117 non-null    object
 13  2018_naissances_totales   117 non-null    float64
 14  2018_naissances_vivantes  117 non-null    float64
 15  2019_naissances_totales   117 non-null    float64
 16  2019_naissances_vivantes  117 non-null    float64
 17  2020_naissances_totales   117 non-null    float64
 18  2020_naissances_vivantes  117 non-null    float64
 19  2021_naissances_totales   117 non-null    float64
 20  2021_naissances_vivantes  117 non-null    float64
 21  2022_naissances_totales   117 non-null    float64
 22  2022_naissances_vivantes  117 non-null    float64
 23  2023_naissances_totales   117 non-null    float64
 24  2023_naissances_vivantes  117 non-null    float64
dtypes: float64(22), object(2), str(1)
memory usage: 25.1+ KB

In [5]:
# Conversion des colonnes 2017 en numérique.
# Ces colonnes avaient été importées en type object.
df["2017_naissances_totales"] = pd.to_numeric(
    df["2017_naissances_totales"],
    errors="coerce"
)

df["2017_naissances_vivantes"] = pd.to_numeric(
    df["2017_naissances_vivantes"],
    errors="coerce"
)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   zone_géographique         118 non-null    str
 1   2012_naissances_totales   117 non-null    float64
 2   2012_naissances_vivantes  117 non-null    float64
 3   2013_naissances_totales   117 non-null    float64
 4   2013_naissances_vivantes  117 non-null    float64
 5   2014_naissances_totales   117 non-null    float64
 6   2014_naissances_vivantes  117 non-null    float64
 7   2015_naissances_totales   117 non-null    float64
 8   2015_naissances_vivantes  117 non-null    float64
 9   2016_naissances_totales   117 non-null    float64
 10  2016_naissances_vivantes  117 non-null    float64
 11  2017_naissances_totales   116 non-null    float64
 12  2017_naissances_vivantes  116 non-null    float64
 13  2018_naissances_totales   117 non-null    float64
 14  2018_naissances_vivantes  117 non-null    float64
 15  2019_naissances_totales   117 non-null    float64
 16  2019_naissances_vivantes  117 non-null    float64
 17  2020_naissances_totales   117 non-null    float64
 18  2020_naissances_vivantes  117 non-null    float64
 19  2021_naissances_totales   117 non-null    float64
 20  2021_naissances_vivantes  117 non-null    float64
 21  2022_naissances_totales   117 non-null    float64
 22  2022_naissances_vivantes  117 non-null    float64
 23  2023_naissances_totales   117 non-null    float64
 24  2023_naissances_vivantes  117 non-null    float64
dtypes: float64(24), str(1)
memory usage: 25.1 KB

In [7]:
df.isna().sum()
# Compte les valeurs manquantes colonne par colonne.

zone_géographique           1
2012_naissances_totales     2
2012_naissances_vivantes    2
2013_naissances_totales     2
2013_naissances_vivantes    2
2014_naissances_totales     2
2014_naissances_vivantes    2
2015_naissances_totales     2
2015_naissances_vivantes    2
2016_naissances_totales     2
2016_naissances_vivantes    2
2017_naissances_totales     3
2017_naissances_vivantes    3
2018_naissances_totales     2
2018_naissances_vivantes    2
2019_naissances_totales     2
2019_naissances_vivantes    2
2020_naissances_totales     2
2020_naissances_vivantes    2
2021_naissances_totales     2
2021_naissances_vivantes    2
2022_naissances_totales     2
2022_naissances_vivantes    2
2023_naissances_totales     2
2023_naissances_vivantes    2
dtype: int64

In [8]:
df[df.isna().any(axis=1)]
# Affiche uniquement les lignes contenant au moins une valeur manquante.
# any(axis=1) signifie :
# "au moins une cellule vide sur la ligne".

,zone_géographique,2012_naissances_totales,2012_naissances_vivantes,2013_naissances_totales,2013_naissances_vivantes,2014_naissances_totales,2014_naissances_vivantes,2015_naissances_totales,2015_naissances_vivantes,2016_naissances_totales,...,2019_naissances_totales,2019_naissances_vivantes,2020_naissances_totales,2020_naissances_vivantes,2021_naissances_totales,2021_naissances_vivantes,2022_naissances_totales,2022_naissances_vivantes,2023_naissances_totales,2023_naissances_vivantes
14,Guadeloupe,5142.0,5057.0,5058.0,4972.0,4866.0,4787.0,4603.0,4498.0,4537.0,...,4506.0,4438.0,4666.0,4578.0,4298.0,4217.0,4089.0,4014.0,3914.0,3845.0
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,"**En 2017, les données du PMSI sont incomplète...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.tail()
# Affiche les 5 dernières lignes du tableau.
# Permet de vérifier que les lignes 117 et 118
# sont bien les lignes de commentaire du fichier.

,zone_géographique,2012_naissances_totales,2012_naissances_vivantes,2013_naissances_totales,2013_naissances_vivantes,2014_naissances_totales,2014_naissances_vivantes,2015_naissances_totales,2015_naissances_vivantes,2016_naissances_totales,...,2019_naissances_totales,2019_naissances_vivantes,2020_naissances_totales,2020_naissances_vivantes,2021_naissances_totales,2021_naissances_vivantes,2022_naissances_totales,2022_naissances_vivantes,2023_naissances_totales,2023_naissances_vivantes
114,Seine-Saint-Denis,28763.0,28447.0,28736.0,28426.0,29619.0,29276.0,29556.0,29235.0,29421.0,...,28579.0,28312.0,28078.0,27775.0,26554.0,26282.0,26527.0,26258.0,25320.0,25064.0
115,Val-de-Marne,20999.0,20793.0,20731.0,20548.0,21588.0,21367.0,21082.0,20904.0,20922.0,...,20733.0,20539.0,20009.0,19835.0,19740.0,19570.0,19101.0,18951.0,17818.0,17654.0
116,Val-d'Oise,19510.0,19335.0,19507.0,19318.0,19695.0,19483.0,19616.0,19394.0,19671.0,...,19805.0,19617.0,19148.0,18963.0,19256.0,19076.0,19173.0,18994.0,17970.0,17764.0
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,"**En 2017, les données du PMSI sont incomplète...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = df.iloc[:-2]
# On supprime les 2 dernières lignes :
# - ligne vide
# - note PMSI

In [11]:
df.shape

# Vérifie le nombre de lignes et de colonnes.

(117, 25)

In [12]:
df.isna().sum()

# Vérifie les valeurs manquantes après nettoyage.

zone_géographique           0
2012_naissances_totales     0
2012_naissances_vivantes    0
2013_naissances_totales     0
2013_naissances_vivantes    0
2014_naissances_totales     0
2014_naissances_vivantes    0
2015_naissances_totales     0
2015_naissances_vivantes    0
2016_naissances_totales     0
2016_naissances_vivantes    0
2017_naissances_totales     1
2017_naissances_vivantes    1
2018_naissances_totales     0
2018_naissances_vivantes    0
2019_naissances_totales     0
2019_naissances_vivantes    0
2020_naissances_totales     0
2020_naissances_vivantes    0
2021_naissances_totales     0
2021_naissances_vivantes    0
2022_naissances_totales     0
2022_naissances_vivantes    0
2023_naissances_totales     0
2023_naissances_vivantes    0
dtype: int64

In [13]:
df.tail()
# Vérification finale du DataFrame après nettoyage.
# Les lignes de commentaire ont été supprimées.

,zone_géographique,2012_naissances_totales,2012_naissances_vivantes,2013_naissances_totales,2013_naissances_vivantes,2014_naissances_totales,2014_naissances_vivantes,2015_naissances_totales,2015_naissances_vivantes,2016_naissances_totales,...,2019_naissances_totales,2019_naissances_vivantes,2020_naissances_totales,2020_naissances_vivantes,2021_naissances_totales,2021_naissances_vivantes,2022_naissances_totales,2022_naissances_vivantes,2023_naissances_totales,2023_naissances_vivantes
112,Essonne,18615.0,18396.0,18599.0,18429.0,18997.0,18816.0,19128.0,18935.0,18747.0,...,18585.0,18397.0,18482.0,18286.0,18538.0,18353.0,18385.0,18223.0,17263.0,17084.0
113,Hauts-de-Seine,24899.0,24647.0,24904.0,24689.0,25015.0,24794.0,24360.0,24149.0,24370.0,...,22905.0,22717.0,21908.0,21716.0,22010.0,21838.0,21079.0,20896.0,19863.0,19713.0
114,Seine-Saint-Denis,28763.0,28447.0,28736.0,28426.0,29619.0,29276.0,29556.0,29235.0,29421.0,...,28579.0,28312.0,28078.0,27775.0,26554.0,26282.0,26527.0,26258.0,25320.0,25064.0
115,Val-de-Marne,20999.0,20793.0,20731.0,20548.0,21588.0,21367.0,21082.0,20904.0,20922.0,...,20733.0,20539.0,20009.0,19835.0,19740.0,19570.0,19101.0,18951.0,17818.0,17654.0
116,Val-d'Oise,19510.0,19335.0,19507.0,19318.0,19695.0,19483.0,19616.0,19394.0,19671.0,...,19805.0,19617.0,19148.0,18963.0,19256.0,19076.0,19173.0,18994.0,17970.0,17764.0

In [14]:
# Une valeur manquante subsiste pour l'année 2017.
# Cela est cohérent avec la note du fichier PMSI indiquant
# que les données 2017 sont incomplètes.

In [15]:
df.describe()  # Permet d'obtenir un résumé statistique des données numériques :
               # count = nombre de valeurs
               # mean = moyenne
               # std = écart-type
               # min / max = valeurs extrêmes
               # 25%, 50%, 75% = quartiles

,2012_naissances_totales,2012_naissances_vivantes,2013_naissances_totales,2013_naissances_vivantes,2014_naissances_totales,2014_naissances_vivantes,2015_naissances_totales,2015_naissances_vivantes,2016_naissances_totales,2016_naissances_vivantes,...,2019_naissances_totales,2019_naissances_vivantes,2020_naissances_totales,2020_naissances_vivantes,2021_naissances_totales,2021_naissances_vivantes,2022_naissances_totales,2022_naissances_vivantes,2023_naissances_totales,2023_naissances_vivantes
count,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,...,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000
mean,28080.487179,27822.709402,27776.461538,27528.641026,27747.700855,27505.111111,27067.692308,26829.290598,26565.213675,26331.333333,...,25461.641026,25247.726496,24867.487179,24648.888889,25037.487179,24817.358974,24526.914530,24313.179487,22801.589744,22602.555556
std,106339.883568,105368.273496,105237.215813,104303.976724,105159.236033,104243.339245,102525.758722,101628.538126,100615.564339,99734.252390,...,96398.305541,95593.735526,94139.719560,93317.924327,94691.447589,93865.129554,92753.382408,91950.933818,86199.378033,85451.016940
min,701.000000,699.000000,654.000000,653.000000,660.000000,652.000000,694.000000,685.000000,662.000000,659.000000,...,584.000000,580.000000,518.000000,513.000000,611.000000,609.000000,587.000000,581.000000,557.000000,553.000000
25%,3527.000000,3498.000000,3469.000000,3442.000000,3382.000000,3355.000000,3232.000000,3208.000000,3210.000000,3187.000000,...,2982.000000,2965.000000,2942.000000,2918.000000,2940.000000,2915.000000,2910.000000,2889.000000,2690.000000,2670.000000
50%,6809.000000,6755.000000,6710.000000,6648.000000,6688.000000,6643.000000,6561.000000,6497.000000,6384.000000,6329.000000,...,5967.000000,5931.000000,5971.000000,5924.000000,6002.000000,5949.000000,5828.000000,5778.000000,5405.000000,5372.000000
75%,16470.000000,16328.000000,16432.000000,16288.000000,16776.000000,16629.000000,16396.000000,16267.000000,16138.000000,16015.000000,...,15716.000000,15588.000000,15404.000000,15269.000000,15435.000000,15304.000000,15162.000000,15022.000000,14155.000000,14046.000000
max,830758.000000,823085.000000,821598.000000,814216.000000,820800.000000,813583.000000,801271.000000,794160.000000,786629.000000,779655.000000,...,754509.000000,748121.000000,736867.000000,730337.000000,742341.000000,735760.000000,727143.000000,720752.000000,676380.000000,670434.000000

In [16]:
df.to_csv(
    "../data/processed/naissances_clean.csv",
    index=False
)

# Sauvegarde le DataFrame nettoyé dans le dossier processed.
# index=False évite d'ajouter une colonne d'index inutile.

## Data Visualisation
Ici, vous réaliserez vos observations, créerez vos graphes dans un premier temps. Une fois qu'ils seront fait, ils seront à intégrer à votre application Streamlit. Considérez donc cet espace comme un bac à sable avant de vous lancer dans le développement de l'application de Data Visualisation.

In [17]:
# Ici, vous réaliserez la visualisation de votre jeu de données